<?=nl2br($entity->getComments())?>

<br /><br />
<table border="1">
	<tr>
	  <td>First Name</td>
      <td><?=$entity->getFirstname()?></td></tr>
	<tr>
	  <td>Last Name</td>
	  <td><?=$entity->getLastname()?></td>
  </tr>
	<tr>
	  <td>Country</td>
	  <td><?=$entity->getCountry()?></td>
  </tr>
	<tr>
	  <td>City</td>
	  <td><?=$entity->getCity()?></td>
  </tr>
	<tr>
	  <td>Postal Code</td>
	  <td><?=$entity->getPostalcode()?></td>
  </tr>
	<tr>
	  <td>Email</td>
	  <td><?=$entity->getEmail()?></td>
  </tr>
	<tr>
	  <td>Mobile No.</td>
	  <td><?=$entity->getMobileno()?></td>
  </tr>
	<tr>
	  <td>Tel. No</td>
	  <td><?=$entity->getPhoneno()?></td>
  </tr>
	<tr>
	  <td>Inquiry Type</td>
	  <td><?=$entity->getInquirytype()?></td>
  </tr>
</table>
