<div style="margin:40px; padding:40px; border:1px solid #ccc;"><div align="center" style="color: #0491c0 !important; font-family: 'Mistral', sans-serif !important; font-size: 26px;">averilla y arrellano</div>
Dear <?=$entity->getFullname()?>,
<br /><br />
Thank you for contacting us.
<br /><br />
We have received your enquiry and will respond to you within 24 hours. For urgent enquiries please call us on one of the telephone numbers below.
<br /><br />
<table>
<tr><td>Philippines:</td><td>+63 927 766 7146, +63 917 270 6046 (Globe)</td></tr>
<tr>
  <td>&nbsp;</td>
  <td>+63 908 921 5266 (Smart)</td>
</tr>
<tr>
  <td>Australia:</td>
  <td>+61 488 059 801 or +61 421 202 000</td>
</tr>
</table>
<br />
Kind regards,
<br />The management</div>