<div class="row">
	<div class="col-md-6 col-md-offset-3">
      <div class="block">
        <div class="block-title">
            <h2><?=$entity->getDate()->format('m/d/Y')?> - <?=$entity->getFirstname()?> <?=$entity->getLastname()?></h2>
        </div>
    
        <p><?=nl2br($entity->getComments())?></p>
        <table class="table table-condensed">
        <tr><td>Country</td><td><?=$entity->getCountry()?></td></tr>
        <tr>
          <td>City</td>
          <td><?=$entity->getCity()?></td>
        </tr>
        <tr>
          <td>Postal Code</td>
          <td><?=$entity->getPostalcode()?></td>
        </tr>
        <tr>
          <td>Email</td>
          <td><?=$entity->getEmail()?></td>
        </tr>
        <tr>
          <td>Mobile No.</td>
          <td><?=$entity->getMobileno()?></td>
        </tr>
        <tr>
          <td>Tel. No</td>
          <td><?=$entity->getPhoneno()?></td>
        </tr>
        <tr>
          <td>Inquiry Type</td>
          <td><?=$entity->getInquirytype()?></td>
        </tr>
        
        </table>
		</div>
    </div>
</div>